### GET request with a header
GET http://127.0.0.1:8000/api/v1.0/price_today/
Accept: application/json

### Post
POST http://127.0.0.1:8000/api/v1.0/price_today/
Content-Type: application/json

{
  "id_fuel": "Gas",
  "id_region": "Київська",
  "id_fuel_operator": "ОККО",
  "price": 1000
}

### update
PUT http://127.0.0.1:8000/api/v1.0/price_today/region_Київська/fuel_Gas/operator_ОККО/
Content-Type: application/json

{
  "id_fuel": "A92",
  "id_region": "Запорізька",
  "id_fuel_operator": "ОККО",
  "price": 11000
}

### delete
DELETE http://127.0.0.1:8000/api/v1.0/price_today/region_Запорізька/fuel_A92/operator_ОККО/
Content-Type: application/json

