# Generated by Django 4.1.3 on 2022-11-12 12:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.validator


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[utils.validator.DateValidator])),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Price must be greater then 0')])),
                ('id_fuel', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fuel', to='fuel.fuel')),
                ('id_fuel_operator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='operator', to='fuel.fueloperator')),
                ('id_region', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='region', to='fuel.region')),
            ],
        ),
    ]
