# Generated by Django 4.1.3 on 2022-11-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0002_pricetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueloperator',
            name='official_site',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
