# Generated by Django 4.1.3 on 2022-11-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0003_alter_fueloperator_official_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueloperator',
            name='official_site',
            field=models.URLField(null=True),
        ),
    ]
