# Generated by Django 4.1.3 on 2022-11-19 13:31

from django.db import migrations, models
import utils.validator


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0004_alter_fueloperator_official_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_task', models.CharField(max_length=250)),
                ('run_date', models.DateField(validators=[utils.validator.DateValidator.date_validator])),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='fuel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='fueloperator',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='pricetable',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='pricetable',
            name='date',
            field=models.DateField(validators=[utils.validator.DateValidator.date_validator]),
        ),
    ]
